### ISSUE TITLE
PING before connection activation fails on secured Redis servers

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#167]
Connections to secured Redis servers are not possible when PING before connection activation is enabled.

The failure stack trace is:

```
com.lambdaworks.redis.RedisConnectionException: Unable to connect to localhost/127.0.0.1:7385
	at com.lambdaworks.redis.AbstractRedisClient.initializeChannel(AbstractRedisClient.java:250)
	at com.lambdaworks.redis.RedisClient.connectStateful(RedisClient.java:445)
	at com.lambdaworks.redis.RedisClient.connectStandalone(RedisClient.java:425)
	at com.lambdaworks.redis.RedisClient.connect(RedisClient.java:356)
	at com.lambdaworks.redis.RedisClient.connect(RedisClient.java:342)
	at com.lambdaworks.redis.ClientOptionsTest.pingBeforeConnectWithAuthentication(ClientOptionsTest.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: com.lambdaworks.redis.RedisCommandExecutionException: NOAUTH Authentication required.
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:272)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at com.lambdaworks.redis.AbstractRedisClient.initializeChannel(AbstractRedisClient.java:237)
	... 17 more
Caused by: com.lambdaworks.redis.RedisCommandExecutionException: NOAUTH Authentication required.
	at com.lambdaworks.redis.protocol.AsyncCommand.completeResult(AsyncCommand.java:86)
	at com.lambdaworks.redis.protocol.AsyncCommand.complete(AsyncCommand.java:76)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:170)
	at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:141)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	... 1 more
```

**Comment by mp911de** [comment]
Done.
