### ISSUE TITLE
ClusterTopologyRefresh fails with NPE on password-secured Cluster nodes if password is not set

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#189]
The `ClusterTopologyRefresh` fails with NPE if the cluster is password protected and no password is provided to connect the cluster.

```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.google.common.base.Splitter.split(Splitter.java:407)
	at com.lambdaworks.redis.cluster.models.partitions.ClusterPartitionParser.parse(ClusterPartitionParser.java:57)
	at com.lambdaworks.redis.cluster.ClusterTopologyRefresh.getNodeSpecificViews(ClusterTopologyRefresh.java:154)
	at com.lambdaworks.redis.cluster.ClusterTopologyRefresh.loadViews(ClusterTopologyRefresh.java:124)
	at com.lambdaworks.redis.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:380)
	at com.lambdaworks.redis.cluster.RedisClusterClient.initializePartitions(RedisClusterClient.java:357)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectClusterAsyncImpl(RedisClusterClient.java:287)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectClusterAsyncImpl(RedisClusterClient.java:271)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectCluster(RedisClusterClient.java:205)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectCluster(RedisClusterClient.java:190)
```

**Comment by mp911de** [comment]
Fixed in 3.x/3.4, already fixed for 4.x
