### ISSUE TITLE
Lettuce fails sometimes at shutdown: DefaultClientResources.shutdown

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#194]
The client shutdown fails because the event executor is terminated before the LatencyEventPublisher subscription is cancelled.

````
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:715)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:300)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:691)
	at io.netty.util.concurrent.AbstractScheduledEventExecutor.removeScheduled(AbstractScheduledEventExecutor.java:206)
	at io.netty.util.concurrent.ScheduledFutureTask.cancel(ScheduledFutureTask.java:153)
	at com.lambdaworks.redis.event.metrics.DefaultCommandLatencyEventPublisher.shutdown(DefaultCommandLatencyEventPublisher.java:53)
	at com.lambdaworks.redis.resource.DefaultClientResources.shutdown(DefaultClientResources.java:314)
(3 more lines...)
```

**Comment by mp911de** [comment]
Fixed.
