### ISSUE TITLE
Getting completely wrong results

### ISSUE THREAD

**Issue by vleushin** [mp911de/lettuce#202]
I've had strange and serious issue on production. It's hard to explain but basically it gets down to getting wrong results, like getting photos of person A, but getting instead photos of person X.

Here are some things I noticed:
* Observed on ```grpc-0.9.0```, ```lettuce-4.0.Final``` or ```lettuce-4.1.Final```, ```netty-4.1.0.Beta6```
* Not observed on ```grpc-0.12.0```, ```lettuce-4.0.Final``` or ```lettuce-4.1.Final```, ```netty-4.1.0.Beta8```
* Starts to happen only after specific exception (will be below)
* Looks like it somehow is mixing up results from
* Redis monitor shows that Redis is getting correct commands

I'm using Amazon ElastiCache so it is standalone Redis 2.8

I pinned down that wrong data is coming from Lettuce, and I suspect Netty. I wonder if you had seen something like this?

**Comment by vleushin** [comment]
I'm calling evalsha method, here is log from redis monitor
```
1455984207.639882 [5 172.31.48.88:46328] "evalsha" "672122f70f1cbab0a778dddfe2454983be4c1dbc" "2" "#{10005248}:profile:photos" "#{10005248}:photos"
1455984207.639905 [5 lua] "lrange" "#{10005248}:profile:photos" "0" "-1"
1455984207.639941 [5 lua] "hmget" "#{10005248}:photos" "41462530" "43559682" "45656834" "47753986" "49851138" "51948290"
1455984207.640023 [5 172.31.48.88:46328] "evalsha" "672122f70f1cbab0a778dddfe2454983be4c1dbc" "2" "#{10264192}:profile:photos" "#{10264192}:photos"
1455984207.640046 [5 lua] "lrange" "#{10264192}:profile:photos" "0" "-1"
1455984207.640056 [5 lua] "hmget" "#{10264192}:photos" "41721474" "45915778" "54304386"
1455984207.640077 [5 172.31.48.88:46328] "evalsha" "672122f70f1cbab0a778dddfe2454983be4c1dbc" "2" "#{7104896}:profile:photos" "#{7104896}:photos"
1455984207.640090 [5 lua] "lrange" "#{7104896}:profile:photos" "0" "-1"
1455984207.640099 [5 lua] "hmget" "#{7104896}:photos" "32270722" "34367874" "44853634" "46950786" "51145090" "53242242"
```

I get profiles of three users (10005248, 10264192, 7104896). List contains their photos, map contains photo data, Lua script to get correct photos from map.

Second time I call method from lettuce, i get same messages in Redis, but different data in lettuce! Meanwhile, in order this to happen, other people have to make requests to this method.

**Comment by vleushin** [comment]
This is how exception looks like after which I start observing this behaviour:
```
2016-02-20 13:35:26.966 [WARN] [nioEventLoopGroup-30-1] [i.n.c.DefaultChannelPipeline] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
rx.exceptions.OnCompletedFailedException: CANCELLED
        at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:90)
        at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onCompleted(OperatorOnErrorResumeNextViaFunction.java:66)
        at com.netflix.hystrix.AbstractCommand$CommandHookApplication$1.onCompleted(AbstractCommand.java:1328)
        at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
        at com.netflix.hystrix.AbstractCommand$DeprecatedOnCompleteWithValueHookApplication$1.onCompleted(AbstractCommand.java:1429)
        at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
        at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onCompleted(OperatorOnErrorResumeNextViaFunction.java:66)
        at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
        at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
        at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onCompleted(AbstractCommand.java:996)
        at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
        at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
        at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onCompleted(AbstractCommand.java:1465)
        at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onCompleted(AbstractCommand.java:1363)
        at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
        at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:110)
        at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
        at rx.internal.operators.OperatorToObservableList$1.onCompleted(OperatorToObservableList.java:93)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:614)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:526)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:255)
        at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
        at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
        at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:110)
        at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
        at rx.internal.operators.OperatorToObservableList$1.onCompleted(OperatorToObservableList.java:93)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:614)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:526)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:815)
        at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onCompleted(OperatorOnErrorResumeNextViaFunction.java:66)
        at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
        at com.lambdaworks.redis.ReactiveCommandDispatcher$ObservableCommand.complete(ReactiveCommandDispatcher.java:111)
        at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:159)
        at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:138)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:155)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:155)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:155)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:155)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:950)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: CANCELLED
        at io.grpc.Status.asRuntimeException(Status.java:431)
        at io.grpc.stub.ServerCalls$ResponseObserver.onCompleted(ServerCalls.java:245)
        at rx.Observable$29.onCompleted(Observable.java:8021)
        at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:84)
        ... 60 more
```

**Comment by vleushin** [comment]
For now I rolled back to version that do not show this behaviour. Would like to hear what you think.

**Comment by mp911de** [comment]
Hi @vleushin, thanks for the report.

There are two issues to untangle. First, I'm not sure where the exception comes from. Looks like it's related to `grpc`. However, the second thing is (and that one worries me more) that the exception falls back into the `CommandHandler` of lettuce. Anything that happens after command completion is skipped. That's nothing terribly worry about but still it can lead to undefined behavior.

As intermediate action, you could handle/filter the exception so it's not propagated back into netty. lettuce can't do anything meaningful with the exception. I'm not fully convinced that the netty version has some impact.

**Comment by mp911de** [comment]
Any updates on this issue?

**Comment by vleushin** [comment]
I was not able to fully investigate issue. It works so far after rollback to older versions. I suspect it has to do with newer GRPC and how they handle threads and errors.

You can close the ticket for now.

**Comment by mp911de** [comment]
Thanks for your feedback. Maybe #214 is of interest for you.
