### ISSUE TITLE
NPE in CommandHandler.write

### ISSUE THREAD

**Issue by cinnom** [mp911de/lettuce#213]
I occasionally get the following stack trace in 4.1.Final and 4.1.1.Final:

```
java.lang.NullPointerException
        at java.util.ArrayDeque.size(ArrayDeque.java:585) ~[?:1.8.0_71]
        at com.lambdaworks.redis.protocol.CommandHandler.write(CommandHandler.java:208) ~[lettuce-4.1.1.Final.jar:?]
        at com.lambdaworks.redis.cluster.ClusterDistributionChannelWriter.write(ClusterDistributionChannelWriter.java:104) ~[lettuce-4.1.1.Final.jar:?]
        at com.lambdaworks.redis.RedisChannelHandler.dispatch(RedisChannelHandler.java:106) ~[lettuce-4.1.1.Final.jar:?]
        at com.lambdaworks.redis.cluster.StatefulRedisClusterConnectionImpl.dispatch(StatefulRedisClusterConnectionImpl.java:189) ~[lettuce-4.1.1.Final.jar:?]
        at com.lambdaworks.redis.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:1726) ~[lettuce-4.1.1.Final.jar:?]
        at com.lambdaworks.redis.AbstractRedisAsyncCommands.smembers(AbstractRedisAsyncCommands.java:916) ~[lettuce-4.1.1.Final.jar:?]
```

Some details on my usage: I have auto-flushing disabled, and I have a single thread that constantly flushes on a fixed delay of 1 ms. I have multiple threads that submit a mix of sync and async calls at somewhere from 10000 to 20000 QPS.

The exception seems benign, and is fairly rare considering my request volume. It seems to pop up once or twice a minute at most.

I can't share the source that causes this as I don't own it, but I will try to reproduce it in new code if required.

**Comment by mp911de** [comment]
Hi @cinnom, 
thanks for reporting the concurrency bug. I did a refactoring of the synchronization code in `CommandHandler` with #211 

I'd like to ask you to use either the `4.2-SNAPSHOT` or the source build to run a test again whether this bug is gone with the 4.2 changes.

**Comment by cinnom** [comment]
@mp911de,

After testing with the latest master, the issue seems to be fixed.

**Comment by mp911de** [comment]
Thanks for testing, great to hear. I'll close this ticket as this issue seems resolved. Feel free to re-open it if the problem persists with lettuce 4.2
