### ISSUE TITLE
Issue while creating redis async connections  using async pool - Threads WAITING

### ISSUE THREAD

**Issue by rohitsardesai83** [mp911de/lettuce#222]
I am using Lettuce version 3.3.2 and I am trying to create multiple redis connection objects to connect to a redis server . I am using an async connection pool for this.

RedisClient client = new RedisClient(host, port, pad);
RedisConnectionPool<RedisAsyncConnection<String, String>> pool = client.asyncPool(30, 300);

I then try to  run multiple threads which do this : 
RedisAsyncConnection<String, String> conn = pool.allocateConnection();
And each thread's run method has a finally block where I call pool.freeConnection();

The program run's fine until this state is reached : 

2016-04-09 13:13:40,913 ERROR [http-bio-127.0.0.1-31811-exec-223][ROOT][io.netty.util.internal.logging.Slf4JLogger 171] allocateConnection Exception: active:61, idle:0
2016-04-09 13:14:10,690 ERROR [http-bio-127.0.0.1-31811-exec-218][ROOT][io.netty.util.internal.logging.Slf4JLogger 171] begin allocateConnection: active:61, idle:0
2016-04-09 13:14:10,717 ERROR [http-bio-127.0.0.1-31811-exec-219][ROOT][io.netty.util.internal.logging.Slf4JLogger 171] allocateConnection Exception: active:61, idle:0
2016-04-09 13:14:40,692 ERROR [http-bio-127.0.0.1-31811-exec-223][ROOT][io.netty.util.internal.logging.Slf4JLogger 171] begin allocateConnection: active:61, idle:0
2016-04-09 13:14:40,697 ERROR [http-bio-127.0.0.1-31811-exec-222][ROOT][io.netty.util.internal.logging.Slf4JLogger 171] allocateConnection Exception: active:61, idle:0

After the pool reaches an active connection object count of 61, all new threads trying to create new objects fail to do so.

Thread dump logs : 

I get this stack trace repeatedly fr multiple threads : 

"nioEventLoopGroup-3-5" #81 prio=10 os_prio=0 tid=0x0000000002203800 nid=0x4ed5 in Object.wait() [0x00007ff51d4f2000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:254)
	- locked <0x00000000fa728f80> (a io.netty.channel.DefaultChannelPromise)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:28)
	at com.lambdaworks.redis.AbstractRedisClient.initializeChannel(AbstractRedisClient.java:212)
	at com.lambdaworks.redis.RedisClient.connectAsync(RedisClient.java:378)
	at com.lambdaworks.redis.RedisClient.connectAsync(RedisClient.java:358)
	at com.lambdaworks.redis.RedisClient$3.createConnection(RedisClient.java:227)
	at com.lambdaworks.redis.RedisClient$3.createConnection(RedisClient.java:224)
	at com.lambdaworks.redis.RedisConnectionPool$1.create(RedisConnectionPool.java:64)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at com.lambdaworks.redis.RedisConnectionPool.allocateConnection
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.lambdaworks.redis.protocol.Command.complete(Command.java:181)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:159)
	at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:138)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

If I am specifying the number of active connections as 300 , then the borrowObject method should be able to create new objects correct ?  Why does the thread have to be WAITING ? From the code , an attempt is made to pollFirst() from the idleObjects dequeue where it blocks.  Since the number of idle object count is 0 , this is blocking and no new objects are getting created . Thoughts ?

**Comment by mp911de** [comment]
This stack trace shows an invocation which completes a `Future` which invokes an action on completion. This action is to connect to a Redis server. In short: You're keeping netty's EventLoopThreads busy and so netty runs out of EventLoopThreads, that's why you see a `WAITING` (blocked) thread.

The longer explanation is: Netty requires some Threads in order to operate properly. Lettuce 3.3.x allocates therefore `Runtime.getRuntime().availableProcessors() * 4` threads. Each Channel (= TCP connection) is assigned to one EventLoop Thread, but one Thread can handle multiple connections. Netty used Thread to perform I/O commands (connect, read, send, …). If Netty runs out of Threads or all Threads are busy, netty cannot perform its requested work, and the effect you see is blocking behavior.

The most important rule when working with event-driven frameworks is not to block the Threads. It's fine to chain invocations or map a result to something different as long as you don't have I/O on your execution path. Calling subsequent commands when a `Future` is completed using lettuce is fine because all calls are queued and I/O happens on different Threads. 

The solution to your problem is to set up an own `ExecutorService` to not block the EventLoop. In general, it's not required to use connection pooling with lettuce, because it auto-reconnects and connections are Thread-safe. Only when using Redis blocking commands (such as `BLPOP`) or transactions (`MULTI`/`EXEC`) one could think about using pooling.

**Comment by mp911de** [comment]
Any update on this issue?

**Comment by rohitsardesai83** [comment]
The issue was worked around by setting a timeout on the channel options when lettuce creates new connections. 
(ChannelOption.SO_KEEPALIVE, true)
(ChannelOption.SO_TIMEOUT, 5)

Earlier , I could see out of 300 connections ( maxTotal ) , 61 were established ( TCP state ESTABLISHED ) , and the rest were in CLOSE_WAIT state.
