### ISSUE TITLE
java.lang.NoClassDefFoundError: rx/Scheduler

### ISSUE THREAD

**Issue by pranabpaul** [mp911de/lettuce#224]
Please let me know how to resolve this.

##I used following libraries in my code:

lettuce-4.1.1.Final.jar
netty-buffer-4.0.34.Final.jar
netty-codec-4.0.34.Final.jar
netty-common-4.0.34.Final.jar
netty-transport-4.0.34.Final.jar
netty-transport-native-epoll-4.0.34.Final.jar
netty-handler-4.0.34.Final.jar
guava-17.0.jar
commons-pool2-2.4.2.jar

##And here is my code:

import com.lambdaworks.redis.RedisClient;
import com.lambdaworks.redis.api.StatefulRedisConnection;

public class Test {

    public static void main(String[] args) {
        RedisClient redisClient = RedisClient.create("rediss://password@redisurl:6380/0");
        StatefulRedisConnection<String, String> connection = redisClient.connect();

        System.out.println("Connected to Redis using SSL");

        connection.close();
        redisClient.shutdown();
    }
}
I am getting following error:

## Logs
Exception in thread "main" java.lang.NoClassDefFoundError: rx/Scheduler
	at com.lambdaworks.redis.AbstractRedisClient.<init>(AbstractRedisClient.java:94)
	at com.lambdaworks.redis.RedisClient.<init>(RedisClient.java:49)
	at com.lambdaworks.redis.RedisClient.create(RedisClient.java:136)
	at Test.main(Test.java:13)
Caused by: java.lang.ClassNotFoundException: rx.Scheduler
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more

**Comment by johnou** [comment]
rxjava-1.1.0 is missing from your classpath.

**Comment by mp911de** [comment]
Hi, 
you also need RxJava and LatencyUtils/HdrHistogram on your class path:

```
<dependency>
    <groupId>io.reactivex</groupId>
    <artifactId>rxjava</artifactId>
    <version>1.1.0</version>
</dependency>

<dependency>
    <groupId>org.latencyutils</groupId>
    <artifactId>LatencyUtils</artifactId>
    <version>2.0.3</version>
</dependency>
```

**Comment by pranabpaul** [comment]
Thanks it worked.
