### ISSUE TITLE
GEORADIUSBYMEMBER, GEORADIUS and GEOPOS run into NPE when using Redis Transactions

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#241]
Geo-Commands `georadiusbymember`, `georadius` and `geopos` fail with when using these together with transactions. `GeoWithinListOutput` and `GeoCoordinatesListOutput` throw `NullPointerException` when decoding the response. Thanks @christophstrobl for the hint.

Code:
```java
redis.multi();
Redis.geopos(key, "Weinheim", "foobar", "Bahn");
List<GeoCoordinates> geopos = (List) redis.exec().get(0);
```

Exception:

```
com.lambdaworks.redis.RedisException: java.lang.NullPointerException

	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:78)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy9.exec(Unknown Source)
	at com.lambdaworks.redis.GeoCommandTest.geoposWithTransaction(GeoCommandTest.java:138)
Caused by: java.lang.NullPointerException
	at com.lambdaworks.redis.output.GeoCoordinatesListOutput.set(GeoCoordinatesListOutput.java:35)
	at com.lambdaworks.redis.output.MultiOutput.set(MultiOutput.java:53)
	at com.lambdaworks.redis.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:193)
	at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:161)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:178)
	at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:157)
```

**Comment by mp911de** [comment]
Fixed.
