### ISSUE TITLE
java.lang.NoSuchMethodError: rx.subjects.PublishSubject.toSerialized()

### ISSUE THREAD

**Issue by CrossfireCurt** [mp911de/lettuce#243]
Hey guys - experiencing the following error when setting up a RedisClusterClient. I am not using RxJava anywhere else in the application, so this is sorta baffling. Any help would be much appreciated.

```
RedisURI redisUri = RedisURI.Builder.redis(closestRedisHost).withPort(redisPort).build();
        RedisClusterClient clusterClient = RedisClusterClient.create(redisUri);
        clusterClient.setOptions(new ClusterClientOptions.Builder()
                .refreshClusterView(true)
                .refreshPeriod(1, TimeUnit.MINUTES)
                .build());
```

```
Exception in thread "main" java.lang.NoSuchMethodError: rx.subjects.PublishSubject.toSerialized()Lrx/subjects/SerializedSubject;
	at com.lambdaworks.redis.event.DefaultEventBus.<init>(DefaultEventBus.java:20)
	at com.lambdaworks.redis.resource.DefaultClientResources.<init>(DefaultClientResources.java:112)
	at com.lambdaworks.redis.resource.DefaultClientResources$Builder.build(DefaultClientResources.java:260)
	at com.lambdaworks.redis.resource.DefaultClientResources.create(DefaultClientResources.java:382)
	at com.lambdaworks.redis.AbstractRedisClient.<init>(AbstractRedisClient.java:94)
	at com.lambdaworks.redis.RedisClient.<init>(RedisClient.java:49)
	at com.lambdaworks.redis.RedisClient.create(RedisClient.java:136)
	at com.commercehub.lumberjack.application.LumberjackGuiceModule.getRedisClusterClient(LumberjackGuiceModule.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
```

**Comment by mp911de** [comment]
`rxjava` is used internally to provide an eventbus. So even if you don't use `rxjava`, it is needed on your class path. Can you check which version of `rxjava` you have on your classpath? Assuming from the stack trace you're using lettuce 4.x, you would need to add `rxjava` in version `1.1.0` to your dependencies.

**Comment by CrossfireCurt** [comment]
Hi Mark - yes I am using 4.x and I have rxjava 1.1.0 on the classpath. I've
also tried 1.1.5 to no avail :(

**Comment by mp911de** [comment]
This issue looks like another library on the class path shadows the lettuce `rxjava` classes. The code in the causing location is:

```java
    public DefaultEventBus(Scheduler scheduler) {
        this.bus = PublishSubject.<Event> create().toSerialized();
        this.scheduler = scheduler;
    }
```

This means, `rx.Scheduler` is found and available. A `rx.subjects.PublishSubject` can be created as well, it is just the call to `toSerialized()` that fails.

Can you inspect your class path for multiple occurrences of `rx.subjects.Subject`. An utility `main` should do the job:

```java
public class main {

    public static void main(String[] args) throws IOException {

        ClassLoader classLoader = main.class.getClassLoader();
        Enumeration<URL> resources = classLoader.getResources("rx/subjects/Subject.class");

        while (resources.hasMoreElements()) {

            URL url = resources.nextElement();
            System.out.println(url);
        }
    }
}

```

(Don't assume you have some sort of agent that rewrites bytecode or does silly things to `final` methods)

**Comment by CrossfireCurt** [comment]
I'll give this a shot! Thanks!

**Comment by mp911de** [comment]
Great to see the issue was resolved. Can you tell me what the cause of the issue was?

**Comment by CrossfireCurt** [comment]
Sure! It was exactly what you suggested. I had a transitive dependency in
the classpath. One of the other packages I included was using an old
version of RxJava.
