### ISSUE TITLE
lettuce ClusterClient fail to connect  when one node is disconnected

### ISSUE THREAD

**Issue by yuvalamar** [mp911de/lettuce#244]
Hi,
I am using lettuce 3.4.3 with redis 3.0.6 in cluster mode(3 master 3 slaves).
When all the nodes are connected  the client works great, but if a I kill one master and the relevant slave is promoted to master (the cluster status is OK but one node is disconnected )
`233be5c60b8c514d5b09f667e01727c96ed1ad3e 10.10.18.122:7003 master - 0 1464158684746 29 connected 4097-10922
8599edb7516c442a2df884cf6ee2b39b37ebb259 10.10.18.124:7006 master - 0 1464158683744 30 connected 0-4096
c69182dcfe8ea2830f2c83a370788d09ea687a00 10.10.18.120:7001 master,fail - 1464158627137 1464158625633 27 disconnected
805db3f7eaaa76d07cc75a902dd98c3e5fffb50d 10.10.18.122:7004 slave 105dbc9282e3367f3e785e517e4954c3410ac40c 0 1464158685750 10 connected
00725d003cb50ccc8b31eea1fb3cac0731e7ba3e 10.10.18.120:7002 slave 233be5c60b8c514d5b09f667e01727c96ed1ad3e 0 1464158684746 29 connected
105dbc9282e3367f3e785e517e4954c3410ac40c 10.10.18.124:7005 myself,master - 0 0 10 connected 10923-16383`

And I am able to work on cluster via redis-cli .
 The lettuce client fails to connect to the cluster
`Exception in thread "main" com.lambdaworks.redis.RedisConnectionException: Unable to connect to /10.10.18.120:7001
	at com.lambdaworks.redis.AbstractRedisClient.initializeChannel(AbstractRedisClient.java:250)
	at com.lambdaworks.redis.AbstractRedisClient.connectAsyncImpl(AbstractRedisClient.java:127)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectClusterAsyncImpl(RedisClusterClient.java:313)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectClusterAsyncImpl(RedisClusterClient.java:275)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectCluster(RedisClusterClient.java:205)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectCluster(RedisClusterClient.java:190)
	at TestRedisson.main(TestRedisson.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.net.ConnectException: Connection refused: no further information: /10.10.18.120:7001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at com.lambdaworks.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
	at com.lambdaworks.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
	at com.lambdaworks.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at com.lambdaworks.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at com.lambdaworks.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at com.lambdaworks.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at com.lambdaworks.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at com.lambdaworks.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:744)`

my config is : 
`        clusterClient = RedisClusterClient.create(redisURIs);
        clusterClient.setOptions(new ClusterClientOptions.Builder()
                .refreshClusterView(true)
                .refreshPeriod(3, TimeUnit.SECONDS)
                .build());
        RedisAdvancedClusterConnection<String, String> con = clusterClient.connectCluster();`

How can I connect to cluster when one node is disconnected ?
Thanks

**Comment by mp911de** [comment]
Hi @yuvalamar 
this is a known issue with lettuce 3.x. Are you limited to use 3.x? If not, please use lettuce 4.1 instead.

**Comment by yuvalamar** [comment]
My system is working only with Java 7 , and as I understood 3.x is java 7 version and 4.x is java 8 only.
in that case I am limited to use 3.x.
Is there any  workaround for this issue?

**Comment by mp911de** [comment]
That's right. There's no workaround for it. Resilience is important to applications but the resilient behavior was not backported to 3.x. I'll tackle this issue. The related ticket for 4.1 was #164.

**Comment by yuvalamar** [comment]
Thanks :) 
Can you estimate when 3.5 version should be released

**Comment by mp911de** [comment]
I have no release date planned for 3.5. I think it will be around June/July. In the meantime, it should be possible to override `connectClusterAsyncImpl(RedisCodec, Supplier<SocketAddress>)` and call `connectAsyncImpl(handler, connection, socketAddressSupplier)` in a loop (like it's done in 4.1).

**Comment by yuvalamar** [comment]
Thanks , I will try it

**Comment by mp911de** [comment]
That's fixed with 196914e. 3.5-SNAPSHOT jar is available in https://oss.sonatype.org/content/repositories/snapshots repo.
