### ISSUE TITLE
Raise netty baseline to 4.1 and keep compatibility to netty 4.0.x

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#274]
Lettuce 4.2 and netty 4.1 do not work together as netty 4.1 breaks binary compatibility in `ByteBuf.forEachByte` (Compile-compatibility was preserved). The code using `ByteBuf.forEachByte` was introduced as part of #212 

```
2016-06-15 08:35:22,153 WARN i.n.c.DefaultChannelPipeline [lettuce-nioEventLoop-8-1] An exception was thrown by a user handler's exceptionCaught() method: java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.forEachByte(IILio/netty/buffer/ByteBufProcessor;)I
    at com.lambdaworks.redis.protocol.RedisStateMachine.readLong(RedisStateMachine.java:232)
    at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:135)
    at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:174)
```

The solution for 4.2.x is to run against netty 4.0 as baseline with ensuring compatibility to netty 4.1 and lettuce 4.3.x raises the baseline to 4.1 and ensures compatibility with 4.0.

**Comment by mp911de** [comment]
Fixed.
