### ISSUE TITLE
Getting "RedisCommandTimeoutException: Command timed out" frequently

### ISSUE THREAD

**Issue by durgeshsuthar1992** [mp911de/lettuce#296]
I am using 4.1.2.Final version to connect to Redis Sentinel cluster.
It works fine for some time after app starts, Then after some time, when I execute any command, It tries to connect and throws RedisCommandTimeoutException. After that, It reconnects automatically. and work fine again. This process goes on.
I am using dropwizard framework and initializing CacheFactory ( which handle connection) when the application starts.

## Logs
```
com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:95) ~[compliance-api.jar:0.0.1]
	at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:74) ~[compliance-api.jar:0.0.1]
	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:63) ~[compliance-api.jar:0.0.1]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[compliance-api.jar:0.0.1]
	at com.sun.proxy.$Proxy70.get(Unknown Source) ~[na:na]
```

##Log when reconnects
```
[lettuce-eventExecutorLoop-5-3] [ConnectionWatchdog]: Reconnecting, last destination was /10.X.X.X:6379
[lettuce-eventExecutorLoop-5-3] [ConnectionWatchdog]: Reconnected to /10.X.X.X:6379.
```

**Comment by mp911de** [comment]
Thanks for your ticket. It sounds a bit like #277. Could you test again with lettuce `4.2.1-SNAPSHOT`? 
The underlying reason is that commands get dispatched sometimes in the wrong order or may get lost while a connection is getting disconnected. `4.2.1-SNAPSHOT` contains a fix for the issue.

**Comment by durgeshsuthar1992** [comment]
Thanks for quick response. I will try with 4.2.1-SNAPSHOT.
I will update how it goes with it.

**Comment by mp911de** [comment]
I was planning to release lettuce 4.2.1 yesterday but I think it's good having the bugfix verified.

**Comment by durgeshsuthar1992** [comment]
Hi,
Can't find 4.2.1-SNAPSHOT version.
```
<dependency>
	<groupId>biz.paluch.redis</groupId>
	<artifactId>lettuce</artifactId>
	<version>4.2.1-SNAPSHOT</version>
</dependency>
```
Am I doing something wrong ?

**Comment by mp911de** [comment]
You probably need to add the Sonatype OSS Snapshot Repository to your
pom.xml, see
http://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository
Durgesh Suthar <notifications@github.com> schrieb am Do., 30. Juni 2016 um
11:26:

**Comment by durgeshsuthar1992** [comment]
It is working fine till now.
Will update again EOD.

Thanks a lot.

**Comment by durgeshsuthar1992** [comment]
Hi,
It is working fine without any issue.
When are you planning to release 4.2.1 version ?

**Comment by mp911de** [comment]
Woohoo! Thanks for testing. I'll release later that day lettuce 4.2.1, should be available in Maven Central by tomorrow.

**Comment by durgeshsuthar1992** [comment]
Cool.
Thanks a lot.
Closing the issue.

**Comment by durgeshsuthar1992** [comment]
Hi Mark,
I am again getting the same issue.

#Adding Warning logs while starting application.
```
WARN  [2016-07-04 19:44:56,077] [Finalizer] [DefaultClientResources]: com.lambdaworks.redis.resource.DefaultClientResources was not shut down properly, shutdown() was not called before it's garbage-collected. Call shutdown() or shutdown(long,long,TimeUnit)
WARN  [2016-07-04 19:44:56,077] [Finalizer] [DefaultClientResources]: com.lambdaworks.redis.resource.DefaultClientResources was not shut down properly, shutdown() was not called before it's garbage-collected. Call shutdown() or shutdown(long,long,TimeUnit)
```

**Comment by mp911de** [comment]
Hi, 

the logs from above indicate that your application performs a GC run but the `DefaultClientResources` were not shut down. That's an application issue (cleanup resources).

**Comment by durgeshsuthar1992** [comment]
Yeah, Got that.
But the same issue of timeout again happening.
```

com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:98) ~[compliance-api.jar:0.0.1]
	at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:77) ~[compliance-api.jar:0.0.1]
	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:48) ~[compliance-api.jar:0.0.1]
	at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:54) ~[compliance-api.jar:0.0.1]
	at com.sun.proxy.$Proxy70.get(Unknown Source) ~[na:na]
```

**Comment by mp911de** [comment]
Can you get a debug log of the time from sending the command with a reconnect until the time the command times out? (Categories/Loggers `com.lambdaworks.redis.protocol` and `com.lambdaworks.redis.protocol.ConnectionWatchdog`). You can email me these if you're concerned about confidential information within the logs.

**Comment by durgeshsuthar1992** [comment]
Emailed you the log with subject line "Logs for Command timeout bug"

**Comment by durgeshsuthar1992** [comment]
It is because of Network issue in the redis cluster.
Tried with a different redis cluster and it worked fine.

Thanks Mark.
Closing the issue.

**Comment by mp911de** [comment]
The indicator for (severe) connection issues is the reconnect part:

```
java.io.IOException: Connection timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_25]
```

`Connection timed out` comes from the operating system layer saying that the TCP retransmit timeout was exceeded. I assume that some packets are sent on the network but either never reach the server or the server’s packet ACK’s get lost.

```
DEBUG [2016-07-05 16:57:08,428] [lettuce-nioEventLoop-6-2] [CommandHandler]: [/1.2.3.4:49286 -> /1.2.3.4:6379] Unexpected exception during request: java.io.IOException: Connection timed out
java.io.IOException: Connection timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_25]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_25]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_25]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_25]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_25]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:221) ~[compliance-api.jar:0.0.1]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:897) ~[compliance-api.jar:0.0.1]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) ~[compliance-api.jar:0.0.1]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[compliance-api.jar:0.0.1]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564) [compliance-api.jar:0.0.1]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505) [compliance-api.jar:0.0.1]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419) [compliance-api.jar:0.0.1]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391) [compliance-api.jar:0.0.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [compliance-api.jar:0.0.1]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145) [compliance-api.jar:0.0.1]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
DEBUG [2016-07-05 16:57:08,428] [lettuce-nioEventLoop-6-2] [ConnectionWatchdog]: [/1.2.3.4:49286 -> /1.2.3.4:6379] channelInactive(io.netty.channel.DefaultChannelHandlerContext@6da1adb3)
DEBUG [2016-07-05 16:57:08,428] [lettuce-nioEventLoop-6-2] [ConnectionWatchdog]: [/1.2.3.4:49286 -> /1.2.3.4:6379] scheduleReconnect()
DEBUG [2016-07-05 16:57:08,428] [lettuce-nioEventLoop-6-2] [ConnectionWatchdog]: [/1.2.3.4:49286 -> /1.2.3.4:6379] Reconnect attempt 1, delay 1ms
```

**Comment by maluqishi** [comment]
i get the same issue use spring-data-redis with lettuce 4.3.1.Final
com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out
        at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:113)
        at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:92)
        at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:63)
        at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy67.keys(Unknown Source)
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.keys(LettuceConnection.java:1052)
        at org.springframework.data.redis.connection.DefaultStringRedisConnection.keys(DefaultStringRedisConnection.java:500)
        at org.springframework.data.redis.core.RedisTemplate$12.doInRedis(RedisTemplate.java:751)
        at org.springframework.data.redis.core.RedisTemplate$12.doInRedis(RedisTemplate.java:748)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:207)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
        at org.springframework.data.redis.core.RedisTemplate.keys(RedisTemplate.java:748)
        at org.springframework.data.redis.core.RedisOperations$keys.call(Unknown Source)

**Comment by mp911de** [comment]
@maluqishi `RedisCommandTimeoutException` is a generic error indicating timeouts. Please file a new issue along with some details (logs, a description what you're doing, …).

**Comment by omjego** [comment]
> Hi,
> 
> the logs from above indicate that your application performs a GC run but the `DefaultClientResources` were not shut down. That's an application issue (cleanup resources).

@mp911de  How should I clean these resources.  How do you properly call shutdown() resources method?

**Comment by mp911de** [comment]
@omjego please post your question to StackOverflow.
