### ISSUE TITLE
ConcurrentModificationException in CommandHandler.queueCommand

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#324]
Under high load, `ConcurrentModificationException` may occur in `CommandHandler.queueCommand`

```
java.util.ConcurrentModificationException java.util.ConcurrentModificationException
        at java.util.ArrayDeque.delete(ArrayDeque.java:539)
        at java.util.ArrayDeque.removeFirstOccurrence(ArrayDeque.java:360)
        at java.util.ArrayDeque.remove(ArrayDeque.java:721)
        at com.lambdaworks.redis.protocol.CommandHandler.queueCommand(CommandHandler.java:428)
        at com.lambdaworks.redis.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:372)
        at com.lambdaworks.redis.protocol.CommandHandler.write(CommandHandler.java:355)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:718)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:710)
        at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:33)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1037)
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1089)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1022)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:394)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by mp911de** [comment]
Fixed.
