### ISSUE TITLE
Geodist throws RedisException caused by "NumberFormatException: empty String" instead of returning null when one or more elements are missing

### ISSUE THREAD

**Issue by ivinskyi** [mp911de/lettuce#362]
Version 4.2.2.Final and probably many older versions

```
redisConnection.sync().geodist("my_geoindex_key", point1, point2, GeoArgs.Unit.m)
```

throws RedisException caused by java.langNumberFormatException if some or all values are not present in geoindex

Relevant stacktrace

```
Caused by: com.lambdaworks.redis.RedisException: java.lang.NumberFormatException: empty String
    at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:109)
    at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:77)
    at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:48)
    at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:54)
...
Caused by: java.lang.NumberFormatException: empty String
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
    at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
    at java.lang.Double.parseDouble(Double.java:538)
    at com.lambdaworks.redis.output.DoubleOutput.set(DoubleOutput.java:25)
    at com.lambdaworks.redis.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:417)
    at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:190)
    at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:202)
    at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:185)
```

**Comment by mp911de** [comment]
This bug occurs if the geoset does not exist and that's a bug in Redis. Redis returns `null` if a member is unknown but an empty string if the geoset is unknown. I filed a ticket: https://github.com/antirez/redis/issues/3512

**Comment by mp911de** [comment]
That's fixed in Redis with https://github.com/antirez/redis/commit/913070a9e85170e89176e5dc9488263cc7327085.
