### ISSUE TITLE
bitfield runs into NPE if executed inside a transaction

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#380]
```
Caused by: java.lang.NullPointerException
	at com.lambdaworks.redis.output.ArrayOutput.set(ArrayOutput.java:38)
	at com.lambdaworks.redis.output.MultiOutput.set(MultiOutput.java:49)
	at com.lambdaworks.redis.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:367)
	at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:147)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:303)
```

**Comment by mp911de** [comment]
Fixed.
