### ISSUE TITLE
RedisCommandTimeoutException with sync MGET

### ISSUE THREAD

**Issue by akepa** [mp911de/lettuce#403]
Hello,

we have seen a problem with RedisClusterClient while testing our code. We have configured the following REDIS cluster, and we do async SETEXs and sync MGETs:

```
> cluster nodes
784fe9ff72cc8f20e1a6c7ccb6b724cd964c1244 ... slave 9865e3bbf28f8af90f86471612369620b1b93fd0 0 1478799151337 4 connected
ce90ec7fcb90dbe9b31c0c73e534ebaefed2d14b ... master - 0 1478799151838 3 connected 10923-16383
44b6aeaa54748d51f4c75eebbde5dfa68e212d13 ... slave a649dc86e2dc21fbfa6fc8760025df6910990e1c 0 1478799150835 5 connected
9865e3bbf28f8af90f86471612369620b1b93fd0 ... myself,master - 0 0 1 connected 0-5460
03fc21f19a927deebd2ddf867d07ed29a2a2f2e5 ... slave ce90ec7fcb90dbe9b31c0c73e534ebaefed2d14b 0 1478799150335 6 connected
a649dc86e2dc21fbfa6fc8760025df6910990e1c ... master - 0 1478799151337 2 connected 5461-10922
```
We connect to the cluster

```
...
AbstractRedisClient redisClient = RedisClusterClient.create(clusterHosts);
((RedisClusterClient)redisClient).setOptions(new ClusterClientOptions.Builder().refreshClusterView(true).refreshPeriod(1, TimeUnit.MINUTES).build());
...
```
Create the connections and try to do the SETEX and MGET. However, the SETEX does not write any value, and the synchronous MGET evenually returns a timeout exception:

```
...
 redisClusterClient = (RedisClusterClient) abstractRedisClient;
            readClusterConnection = redisClusterClient.connect(LazyCacheProtobufRedisCodec.INSTANCE);
            writeClusterConnection = redisClusterClient.connect(LazyCacheProtobufRedisCodec.INSTANCE);
            readClusterConnection.setAutoFlushCommands(false);
...
    public RedisClusterCommands<String, Message> readSync(){
            return readClusterConnection.sync().mget(formattedKeys.stream().toArray(String[]::new));
    }

    public RedisClusterAsyncCommands<String, Message> writeAsync(){
            return writeClusterConnection.async().setex(entry.getKey().format(), expiration, entry.getValue());
    }

```

```
Caused by: com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:98)
	at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:77)
	at com.lambdaworks.redis.cluster.StatefulRedisClusterConnectionImpl$ClusterFutureSyncInvocationHandler.handleInvocation(StatefulRedisClusterConnectionImpl.java:330)
	at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:54)
	at com.sun.proxy.$Proxy153.mget(Unknown Source)
```

We have tried to replaced the previous code by the former API and it seems to work fine:

```
...
redisClusterClient = (RedisClusterClient) abstractRedisClient;
readClusterConnection =redisClusterClient.connectCluster(LazyCacheProtobufRedisCodec.INSTANCE);
writeClusterConnection = redisClusterClient.connectClusterAsync(LazyCacheProtobufRedisCodec.INSTANCE);
writeClusterConnection.setAutoFlushCommands(false);
...

    public List<Message> readSync(List<String> formattedKeys){
           return readClusterConnection.mget(formattedKeys.stream().toArray(String[]::new));
    }

    public RedisFuture<String> writeAsync(long expiration, Map.Entry<RateAmountCachedUpdaterKey, Message> entry){
           return writeClusterConnection.setex(entry.getKey().format(), expiration, entry.getValue());
    }
```

Could you please advise if there anything in the underlying implementation of these methods that could explain that it is working with the deprecated API but not with the new one?

We are using version 4.2.2-Final.

Thanks, and best regards,
Adam.

**Comment by mp911de** [comment]
`setAutoFlushCommands(false)` is intended for batching use and one has to call `flushCommands()` once you're ready to send all queued commands to Redis. 

Did you check the outcome of `SETEX` and made sure the command arrives at your cluster node (`redis-cli` with `MONITOR` enabled)?

**Comment by mp911de** [comment]
Any update on this issue?

**Comment by mp911de** [comment]
Closing this ticket because of inactivity.
