### ISSUE TITLE
How can I use it in android?

### ISSUE THREAD

**Issue by gotounix** [mp911de/lettuce#407]
I use lettuce-4.3.0.Final in Android Studio with JDK 1.8 and get these errors:
```
Information:Gradle tasks [:app:clean, :app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :app:assembleDebug]
Error:PARSE ERROR:
Error:unsupported class file version 52.0
Error:...while parsing com/lambdaworks/codec/Base16.class
Error:1 error; aborting
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
Information:BUILD FAILED
```

I use lettuce-3.5.0.Final in Android Studio and build successful, but I get these errors when run the app.
```
11-21 13:45:03.880 30065-30065/net.hello.test E/MtaSDK: java.lang.NoClassDefFoundError: Failed resolution of: Lio/netty/buffer/PooledByteBufAllocator;
                                                         at com.lambdaworks.redis.AbstractRedisClient.<clinit>(AbstractRedisClient.java:54)
                                                         at com.lambdaworks.redis.RedisClient.create(RedisClient.java:132)
                                                         at net.hello.test.MainActivity.onCreate(MainActivity.java:98)
                                                         at android.app.Activity.performCreate(Activity.java:6117)
                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2715)
                                                         at android.app.ActivityThread.access$800(ActivityThread.java:184)
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1566)
                                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                                         at android.os.Looper.loop(Looper.java:194)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5826)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "io.netty.buffer.PooledByteBufAllocator" on path: DexPathList[[dex file "/data/data/net.hello.test/files/instant-run/dex/slice-support-annotations-23.2.0_5d3a6b5a1bb732951b5916bfcc20d1ae3e0a5fcf-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-libammsdk_ce71d007dbc87b6060d94c6eca86e4371cc88a3f-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-lettuce-3.5.0.Final_388651610a47f3bf32ab5b4da08a377ca9656b3d-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-internal_impl-23.2.0_95f1e736d08222b54cf635648e5d2590f6e64ffa-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-com.android.support-support-vector-drawable-23.2.0_094140fc8aebd8bd8be04a90a32b3b3814b15c3a-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-com.android.support-support-v4-23.2.0_e7edf5795eb5771b6253e0fe9d6a4dd24dc8dcab-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.2.0_42aa5a4a5a87c4e800b03f77374a78395c007f72-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-23.2.0_3f14363d95f092024f78901c604da7ef67fa228f-classes.dex"],nativeLibraryDirectories=[/data/app/net.hello.test-2/lib/arm, /vendor/lib, /system/lib, /vendor/lib, /system/lib]]
                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                         at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                         at com.lambdaworks.redis.AbstractRedisClient.<clinit>(AbstractRedisClient.java:54) 
                                                         at com.lambdaworks.redis.RedisClient.create(RedisClient.java:132) 
                                                         at net.hello.test.MainActivity.onCreate(MainActivity.java:98) 
                                                         at android.app.Activity.performCreate(Activity.java:6117) 
                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123) 
                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2715) 
                                                         at android.app.ActivityThread.access$800(ActivityThread.java:184) 
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1566) 
                                                         at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                         at android.os.Looper.loop(Looper.java:194) 
                                                         at android.app.ActivityThread.main(ActivityThread.java:5826) 
                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009) 
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804) 
                                                     	Suppressed: java.lang.ClassNotFoundException: Didn't find class "io.netty.buffer.PooledByteBufAllocator" on path: DexPathList[[zip file "/data/app/net.hello.test-2/base.apk"],nativeLibraryDirectories=[/data/app/net.hello.test-2/lib/arm, /vendor/lib, /system/lib]]
                                                     		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.
11-21 13:45:03.884 30065-30065/net.hello.test E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: net.hello.test, PID: 30065
                                                             java.lang.NoClassDefFoundError: Failed resolution of: Lio/netty/buffer/PooledByteBufAllocator;
                                                                 at com.lambdaworks.redis.AbstractRedisClient.<clinit>(AbstractRedisClient.java:54)
                                                                 at com.lambdaworks.redis.RedisClient.create(RedisClient.java:132)
                                                                 at net.hello.test.MainActivity.onCreate(MainActivity.java:98)
                                                                 at android.app.Activity.performCreate(Activity.java:6117)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2715)
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:184)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1566)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5826)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "io.netty.buffer.PooledByteBufAllocator" on path: DexPathList[[dex file "/data/data/net.hello.test/files/instant-run/dex/slice-support-annotations-23.2.0_5d3a6b5a1bb732951b5916bfcc20d1ae3e0a5fcf-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-libammsdk_ce71d007dbc87b6060d94c6eca86e4371cc88a3f-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-lettuce-3.5.0.Final_388651610a47f3bf32ab5b4da08a377ca9656b3d-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-internal_impl-23.2.0_95f1e736d08222b54cf635648e5d2590f6e64ffa-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-com.android.support-support-vector-drawable-23.2.0_094140fc8aebd8bd8be04a90a32b3b3814b15c3a-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-com.android.support-support-v4-23.2.0_e7edf5795eb5771b6253e0fe9d6a4dd24dc8dcab-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.2.0_42aa5a4a5a87c4e800b03f77374a78395c007f72-classes.dex", dex file "/data/data/net.hello.test/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-23.2.0_3f14363d95f092024f78901c604da7ef67fa228f-classes.dex"],nativeLibraryDirectories=[/data/app/net.hello.test-2/lib/arm, /vendor/lib, /system/lib, /vendor/lib, /system/lib]]
                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                 at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                 at com.lambdaworks.redis.AbstractRedisClient.<clinit>(AbstractRedisClient.java:54) 
                                                                 at com.lambdaworks.redis.RedisClient.create(RedisClient.java:132) 
                                                                 at net.hello.test.MainActivity.onCreate(MainActivity.java:98) 
                                                                 at android.app.Activity.performCreate(Activity.java:6117) 
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123) 
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2715) 
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:184) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1566) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                 at android.os.Looper.loop(Looper.java:194) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5826) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804) 
                                                             	Suppressed: java.lang.ClassNotFoundException: Didn't find class "io.netty.buffer.PooledByteBufAllocator" on path: DexPathList[[zip file "/data/app/net.hello.test-2/base.apk"],nativeLibraryDirectories=[/data/app/net.hello.test-2/lib/arm, /vendor/lib, /system/lib]]
```

How to deal with this, thanks.

**Comment by mp911de** [comment]
I'm not an Andriod developer but I'd say you might want to add lettuce's dependencies (Guava, Netty, RxJava1).

**Comment by mp911de** [comment]
Closing because of inactivity.
