### ISSUE TITLE
Slow consumer - Class not found

### ISSUE THREAD

**Issue by magdkudama** [mp911de/lettuce#478]
Hi,

Using latest Lettuce version.

I was testing the behaviour with a very slow consumer in a pub/sub environment, and I had this error:

```
16:41:57.578 [lettuce-nioEventLoop-5-1] WARN  c.l.redis.protocol.CommandHandler - [chid=0x1, channel=0x823e29f1, /127.0.0.1:49536 -> ] Input not readable true, 0
Exception in thread "lettuce-nioEventLoop-5-1" java.lang.NoClassDefFoundError: io/netty/buffer/PoolArena$1
```

Is this just to due with Netty, or should it be fixed by Lettuce?

**Comment by magdkudama** [comment]
Sorry, full stack trace

```
16:41:57.578 [lettuce-nioEventLoop-5-1] WARN  c.l.redis.protocol.CommandHandler - [chid=0x1, channel=0x823e29f1, /127.0.0.1:49536 -> ] Input not readable true, 0
Exception in thread "lettuce-nioEventLoop-5-1" java.lang.NoClassDefFoundError: io/netty/buffer/PoolArena$1
	at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:288)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:470)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:440)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:432)
	at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:289)
	at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:280)
	at io.netty.buffer.PoolThreadCache.free0(PoolThreadCache.java:253)
	at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:249)
	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:393)
	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:370)
	at io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:226)
	at io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:146)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mp911de** [comment]
Hi, 

which netty version do you use? Make also sure, that you use the same version across all netty components. It looks as if you had multiple netty versions on the classpath.

**Comment by magdkudama** [comment]
My bad I guess, sorry. I was using Lettuce `4.3.1.Final`, which is using Netty 4.1.6, but as I'm using Unix Domain Sockets, I added `netty-transport-native-epoll:4.1.8.Final`, I should probably downgrade that to match `4.1.6`.
