### ISSUE TITLE
CI: Build ran into OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by mp911de** [mp911de/lettuce#84]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 52.403 sec <<< FAILURE! - in com.lambdaworks.redis.LettucePerformanceTest
testPerformance(com.lambdaworks.redis.LettucePerformanceTest)  Time elapsed: 51.952 sec  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.lambdaworks.redis.LettucePerformanceTest.testPerformance(LettucePerformanceTest.java:60)
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by mp911de** [comment]
Reason is the log capturing while test run. Disabled for performance tests.
