### ISSUE TITLE
com.lambdaworks.redis.RedisCommandExecutionException: MOVED 15446 127.0.0.1:7005

### ISSUE THREAD

**Issue by wanggit** [mp911de/lettuce#95]
<dependency>
		  <groupId>biz.paluch.redis</groupId>
		  <artifactId>lettuce</artifactId>
		  <version>3.2.Final</version>
		</dependency>
---------------------------------------------
		List<RedisURI> initialUris = new ArrayList<RedisURI>();
		initialUris.add(RedisURI.Builder.redis("182.92.10.64", 7003).build());
		initialUris.add(RedisURI.Builder.redis("182.92.10.64", 7004).build());
		initialUris.add(RedisURI.Builder.redis("182.92.10.64", 7005).build());
		RedisClusterClient rcc = new RedisClusterClient(initialUris);
		RedisClusterAsyncConnection<String, String> connection = rcc.connectClusterAsync();
		connection.set("test.name", "wanggang");
		System.out.println( connection.get("test.name") );
--------------------------------------------
but, I get this exception
com.lambdaworks.redis.RedisException: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:7005
	at com.lambdaworks.redis.cluster.PooledClusterConnectionProvider.getConnection(PooledClusterConnectionProvider.java:67)
	at com.lambdaworks.redis.cluster.ClusterDistributionChannelWriter.write(ClusterDistributionChannelWriter.java:69)
	at com.lambdaworks.redis.RedisChannelHandler.dispatch(RedisChannelHandler.java:111)
	at com.lambdaworks.redis.RedisAsyncConnectionImpl.dispatch(RedisAsyncConnectionImpl.java:1595)
	at com.lambdaworks.redis.RedisAsyncConnectionImpl.set(RedisAsyncConnectionImpl.java:772)
	at wg.spring.data1.controller.CityController.testRedis(CityController.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:213)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:526)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:655)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:146)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:7005
	at com.lambdaworks.redis.AbstractRedisClient.initializeChannel(AbstractRedisClient.java:214)
	at com.lambdaworks.redis.AbstractRedisClient.connectAsyncImpl(AbstractRedisClient.java:96)
	at com.lambdaworks.redis.cluster.RedisClusterClient.connectAsyncImpl(RedisClusterClient.java:134)
	at com.lambdaworks.redis.cluster.PooledClusterConnectionProvider$KeyedConnectionFactory.create(PooledClusterConnectionProvider.java:98)
	at com.lambdaworks.redis.cluster.PooledClusterConnectionProvider$KeyedConnectionFactory.create(PooledClusterConnectionProvider.java:85)
	at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1041)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:357)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:279)
	at com.lambdaworks.redis.cluster.PooledClusterConnectionProvider.getConnection(PooledClusterConnectionProvider.java:63)
	... 42 more
Caused by: java.net.ConnectException: Connection refused: no further information: /127.0.0.1:7005
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)

*******************************
help me.

**Comment by mp911de** [comment]
@wanggit The reported behavior is related to your cluster setup. Your cluster is set up with `CLUSTER MEET 127.0.0.1 (PORT)` so the cluster knows its nodes only by `127.0.0.1`. Localhost addresses are not translated by lettuce into external addresses.

You can fix the problem by setting up the cluster with `CLUSTER MEET 182.92.10.64 7003`, `CLUSTER MEET 182.92.10.64 7004` and so on.

**Comment by wanggit** [comment]
thanks for answer 
I modify code like this
-----------------
List<RedisURI> initialUris = new ArrayList<RedisURI>();
		initialUris.add(RedisURI.Builder.redis("182.92.10.64", 7003).build());
		initialUris.add(RedisURI.Builder.redis("182.92.10.64", 7004).build());
		initialUris.add(RedisURI.Builder.redis("182.92.10.64", 7005).build());
		RedisClusterClient rcc = new RedisClusterClient(initialUris);
		
		RedisClusterAsyncConnection<String, String> connection = rcc.connectClusterAsync();
		connection.clusterMeet("182.92.10.64", 7003);
		connection.clusterMeet("182.92.10.64", 7004);
		connection.clusterMeet("182.92.10.64", 7005);
		connection.set("test.name", "wanggang");
		System.out.println( connection.get("test.name") );
--------------------
The Error not fixed; 
My code is wrong or redis setup is wrong?

**Comment by mp911de** [comment]
Did you reset your cluster configuration before? What is the output of `CLUSTER NODES` when you issue it using `redis-cli -h 182.92.10.64 -p 7003`?

**Comment by wanggit** [comment]
thanks, you are right.
